default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  port: 5432
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db

development:
  <<: *default
  database: cumplo_development

test:
  <<: *default
  database: cumplo_test

production:
  <<: *default
  database: cumplo_production
