default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  port: 5432

default_local: &default_local
  host: localhost
  username: pguser
  password: admin

development:
  <<: *default
  <<: *default_local
  database: cumplo_development

test:
  <<: *default
  <<: *default_local
  database: cumplo_test

production:
  <<: *default
  database: cumplo_production
